***********************************************************************
*
* (c) Copyright IBM Corporation 2024.
*     Copyright Contributors to the GenevaERS Project.
* SPDX-License-Identifier: Apache-2.0
*
***********************************************************************
*
*   Licensed under the Apache License, Version 2.0 (the "License");
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
*   or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
***********************************************************************
*
*   This module is called by the assembler/3GL/etc code, e.g. GVBMR95
*   to communicate with GvbJavaDaemon. It employs WAIT POST logic to
*   pass requests to the daemon which loads and executes Java classes
*   and methods dynamically.
*
*   The assembler/3GL application can be multi-threaded and the number
*   of Java threads it requires is indicated by the "INIT" call.
*
*   The "SEND" call is used to request execution of a particular Java
*   class and method, also supplying send and receive data buffers.
*
***********************************************************************
*
*        GVBUR70 CALL INTERFACE
*
UR70STR  DSECT
UR70VERS DS    H                 API version number == 1
UR70FLG1 DS    X                 Flag 1: M indicates called by MR95 
UR70FLG2 DS    X                 Flag 2: Indicates method argument type
UR70FUN  DS    CL8               Function
UR70OPNT DS   0H                 Number of Java threads requested
UR70OPT  DS    CL8               Options
UR70CLSS DS    CL32              Java class requested
UR70METH DS    CL32              Java method requested
UR70LSND DS    F                 Length of data sent to Java (send)
UR70LRCV DS    F                 Length of data expected from Java
UR70LRET DS    F                 Actual length received from Java
UR70RETC DS    F                 Return code from GVBUR70
UR70ANCH DS    A                 Anchor initialize zero but don't alter
UR70JRET DS    F                 Return code from Java method
         DS    F
UR70LEN  EQU   *-UR70STR
*
