/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zOSInfo */

#ifndef _Included_zOSInfo
#define _Included_zOSInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zOSInfo
 * Method:    showZos
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zOSInfo_showZos
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
